version: "2.2"
services:
  app:
    build: ./app
    env_file: database.conf
    links:
      - db
    ports:
      - 90:80
# Port is 90 as apache server is already running on local

  db:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
